---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
    name: cpu-deployment
spec:
    replicas: 1
    template: 
        metadata: 
            labels:
                app: cpu
        spec:
            containers:
            - name: main
              image: intelsdi/snap:alpine_test
              env:
                - name: SNAP_VERSION
                  value: "latest"
              imagePullPolicy: "IfNotPresent"